export const ALL_PROJECTS = 'ALL_PROJECTS';
export const ONE_PROJECT = 'ONE_PROJECT';
export const TOOGLE_SIDEBAR = 'TOOGLE_SIDEBAR';
export const CHANGE_TASK_TO_DONE = 'CHANGE_TASK_TO_DONE';
export const SET_UP_SOCKET = 'SET_UP_SOCKET';
export const ALL_MESSAGES = 'ALL_MESSAGES';